version: "2"

services:
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    labels:
      kompose.service.type: clusterip

  pgadmin:
    extends:
      file: docker-compose.yaml
      service: pgadmin
    labels:
      kompose.service.type: clusterip

  redis:
    extends:
      file: docker-compose.yaml
      service: redis
    labels:
      kompose.service.type: clusterip

  node:
    image: ${REGISTRY}/node:${TAG}
    build:
      context: './'
    working_dir: /indexer
    command: npm run start
    env_file:
      - .env
    ports:
      - "80:80"
    restart: always
    depends_on:
      - postgres
      - pgadmin
      - redis
    labels:
      kompose.service.type: "loadbalancer"

networks:
  local:
    driver: overlay
