version: "2"

services:
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    networks:
      - service-net
    labels:
      kompose.service.type: clusterip

  pgadmin:
    extends:
      file: docker-compose.yaml
      service: pgadmin
    networks:
      - service-net
    labels:
      kompose.service.type: clusterip

  redis:
    extends:
      file: docker-compose.yaml
      service: redis
    networks:
      - service-net
    labels:
      kompose.service.type: clusterip

  node:
    image: ${REGISTRY}/node:${TAG}
    build:
      context: './'
    working_dir: /indexer
    command: npm run start
    env_file:
      - .env
    ports:
      - "7979"
    restart: always
    depends_on:
      - postgres
      - pgadmin
      - redis
    networks:
      - service-net
    labels:
      kompose.service.type: nodeport
      kompose.service.nodeport.port: "31000"

networks:
  local:
    driver: bridge
  service-net:

